### ISSUE TITLE
Installing OS X QGIS breaks .profile

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgis_installer#48]
@systemed wrote:

```
Installing QGIS for OS X creates a .bash_profile file containing
various environment variables.

If the user already has a .profile (but no .bash_profile), this will no longer 
work after .bash_profile has been created.
```

Moved from https://github.com/nextgis/nextgisqgis/issues/37

**Comment by BishopGIS** [comment]
```
“After reading [/etc/profile], [bash] looks for ~/.bash_profile, ~/.bash_login,
and ~/.profile, in that order, and reads and executes commands from the 
first one that exists and is readable.”
```

Need to fix here https://github.com/nextgis/nextgis_installer/blob/master/qtifw/src/libs/installer/ng_fileenvironmentvariablesoperation.cpp#L144 and in installer ``qs`` scripts to check which of files ``.profile`` or ``.bash_profile`` exists and use exist one. If no files exist create ``.bash_profile``.

**Comment by systemed** [comment]
Thanks for fixing.

Out of interest, is there a reason not to set the env vars in the app's plist, rather than editing the profile? (See https://superuser.com/questions/476752/setting-environment-variables-in-os-x-for-gui-applications )

I had a foul-up recently where my PostGIS installation was trying to use QGIS's PROJ_LIB and GDAL_DATA locations, rather than my systemwide proj/GDAL. Ideally the QGIS locations should just be used by QGIS.

**Comment by BishopGIS** [comment]
This variables (in .profile) used only in console applications like orginfo, gdalwarp, etc. in terminal sessions. They are not affected on GUI applications.

For GUI applications plists created too. See: https://github.com/nextgis/nextgis_installer/blob/master/qtifw_scripts/packages/com.nextgis.spatial.gdal/meta/installscript.qs#L14-L33

**Comment by systemed** [comment]
Excellent, thanks. So I can disable those variables if I want to keep using my systemwide tools.

**Comment by BishopGIS** [comment]
Yes, certainly.
